my:
  greeting: Hello World from github server
  list:
    values: This is application.yml from github repo
    
db: 
  connection: connection-string-here-from-config-server
  host: 127.0.0.1
  port: 1200
